### ISSUE TITLE
Predict.py runtime error 

### ISSUE THREAD

**Issue by sirison** [gasparian/CRNN_OCR_lite#5]
Hi , 

I'm getting the below error while running the predict function.

(User) C:\Jagadesh\529\CRNN_OCR_lite>python predict.py --G 0 --model_path C:\Jagadesh\529\CRNN_OCR_lite\models\OCR_IAM_ver1 --image_path C:\Jagadesh\529\CRNN_OCR_lite\input --result_path C:\Jagadesh\529\CRNN_OCR_lite\output
Using TensorFlow backend.
WARNING:tensorflow:From C:\Users\jsiriso\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-05-08 16:06:16.317501: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
WARNING:tensorflow:From C:\Users\jsiriso\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\keras\backend\tensorflow_backend.py:3368: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Traceback (most recent call last):
  File "predict.py", line 105, in <module>
    model = load_custom_model(model_path, model_name='/model.json', weights="/final_weights.h5")
  File "C:\Jagadesh\529\CRNN_OCR_lite\utils.py", line 327, in load_custom_model
    model = model_from_json(loaded_model_json, custom_objects={'BilinearInterpolation': BilinearInterpolation})
  File "C:\Users\jsiriso\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\keras\engine\saving.py", line 368, in model_from_json
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Users\jsiriso\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "C:\Users\jsiriso\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Users\jsiriso\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\keras\engine\network.py", line 1027, in from_config
    process_node(layer, node_data)
  File "C:\Users\jsiriso\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\keras\engine\network.py", line 986, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "C:\Users\jsiriso\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\jsiriso\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\keras\layers\core.py", line 682, in call
    return self.function(inputs, **arguments)
  File "/data/data/CRNN_OCR_keras/utils.py", line 99, in ctc_lambda_func
IndexError: tuple index out of range

**Comment by gasparian** [comment]
@sirison 
1. Check that you're using `tensorflow==1.8` and `keras==2.2.2`
2. If you don't use GPU, set `--G` argument to `-1` (the CPU will be using if the arg is less than zero)
3. Try to reproduce this with the provided docker image.

**Comment by gasparian** [comment]
@sirison 
Actually, in the latest commit, I've added a check for GPUs availability into `predict.py`.

**Comment by sirison** [comment]
@gasparian 

I tried all the three suggestion and it didn't work even after that. 

while trying to reproduce using docker image I got the below error.

PS C:\E_Drive\Data \Projects\529 \codes\CRNN_OCR_lite> docker run  --rm -it -v /home:/data -p 4005:8000 gasparjan/crnn_ocr:latest
root@f48ae675ac73:/# python predict.py --G 0 \
>                    --model_path /data/data/CRNN_OCR_keras/data/OCR_IAM_ver1 \
>                    --image_path /data/data/CRNN_OCR_keras/data/IAM_processed \
>                    --num_instances 128 --result_path /tmp  --max_len 23
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "predict.py", line 12, in <module>
    from keras import backend as K
  File "/usr/local/lib/python3.6/dist-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help

**Comment by gasparian** [comment]
@sirison 
Ok! I'll check it and come up with the solution ;)

**Comment by sirison** [comment]
thank you , even I'll try to make it work on windows.

**Comment by gasparian** [comment]
@sirison 
1. About your first error - it seems like it can be some environmental issues. All works well for me, with CPU and GPU, using another docker image from https://github.com/ufoym/deepo.
2. The last error raises because of using `docker` instead of `nvidia-docker`. So you can just install `nvidia-docker` and run it all again.

**Comment by sirison** [comment]
@gasparian  

I tried it in Ubuntu 18.04 and installed all the required tools from docker file manually but no luck ..

below is the error ..

(User)sirison@sirison-VirtualBox:/media/MY/529/CRNN_OCR_Lite$ python predict.py --G -1 --model_path /media/MY/529/CRNN_OCR_Lite/models/OCR_IAM_ver1 --image_path /media/MY/529/CRNN_OCR_Lite/input --result_path /media/MY/529/CRNN_OCR_Lite/output --validate --num_instances 128  --max_len 23
Using TensorFlow backend.
2019-05-14 13:00:12.561284: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-05-14 13:00:12.581548: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_UNKNOWN
2019-05-14 13:00:12.581629: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:145] kernel driver does not appear to be running on this host (sirison-VirtualBox): /proc/driver/nvidia/version does not exist
 [INFO] Predicting... 
Traceback (most recent call last):
  File "predict.py", line 165, in <module>
    predicted = model.predict_generator(reader.run_generator(fnames, bboxs=bboxs, downsample_factor=2), steps=steps)
  File "/home/sirison/.local/share/canopy/edm/envs/User/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/sirison/.local/share/canopy/edm/envs/User/lib/python3.5/site-packages/keras/engine/training.py", line 1519, in predict_generator
    verbose=verbose)
  File "/home/sirison/.local/share/canopy/edm/envs/User/lib/python3.5/site-packages/keras/engine/training_generator.py", line 450, in predict_generator
    outs = model.predict_on_batch(x)
  File "/home/sirison/.local/share/canopy/edm/envs/User/lib/python3.5/site-packages/keras/engine/training.py", line 1266, in predict_on_batch
    x, _, _ = self._standardize_user_data(x)
  File "/home/sirison/.local/share/canopy/edm/envs/User/lib/python3.5/site-packages/keras/engine/training.py", line 749, in _standardize_user_data
    exception_prefix='input')
  File "/home/sirison/.local/share/canopy/edm/envs/User/lib/python3.5/site-packages/keras/engine/training_utils.py", line 137, in standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected the_labels to have shape (10,) but got array with shape (23,)

**Comment by gasparian** [comment]
@sirison 
Hm. Despite cuda-errors at the beginning, it seems like the model has been loaded and even prediction started. The last error is about `max_len` argument (max length of the input strings) - I think you must set it to `10` instead of `23`, according to your dataset properties...

**Comment by sirison** [comment]
@gasparian  
Here I'm using trained model provided by you and testing it on IAM data sets from processed IAM files.

**Comment by gasparian** [comment]
@sirison 
Hm, then it's weird...
I can't reproduce this error, so it can be still connected with environment...
I'll build and push a new docker image for CPU only and report in this thread.

**Comment by gasparian** [comment]
@sirison 
So I've tested and added CPU-only build in the last commit. You need just pull it from Dockerhub and try again :)
`docker pull gasparjan/crnn_ocr:cpu`
then run docker like this: 
```
docker run --rm -it -v /home:/data \
                    -p 8004:8000 gasparjan/crnn_ocr:cpu
```

**Comment by sirison** [comment]
@gasparian  , thanks a ton !!! , the above image worked.
